branch-defaults:
  default:
    environment: Udagramapis-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Udagramapis-env:
    branch: null
    repository: null
global:
  application_name: udagram-apis
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
